# Generated by Django 6.0.3 on 2026-03-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misto_prace', models.CharField(max_length=255)),
                ('datum', models.DateField()),
                ('popis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pracovnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=255)),
                ('cinnost', models.CharField(max_length=255)),
                ('kvalifikace', models.CharField(max_length=255)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracovnici', to='formular.formular')),
            ],
        ),
    ]
