# Generated by Django 6.0.3 on 2026-03-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
