# Generated by Django 6.0.3 on 2026-03-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0002_formular_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='zhotovitel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
