# Generated by Django 6.0.3 on 2026-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0003_formular_zhotovitel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formular',
            name='telefon',
        ),
        migrations.AddField(
            model_name='formular',
            name='jmenoPrijmeni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='kontakt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='telefonMajitel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='telefonZadavatel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='zadavatel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
