# Generated by Django 6.0.3 on 2026-03-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0004_remove_formular_telefon_formular_jmenoprijmeni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formular',
            name='popis',
        ),
        migrations.AddField(
            model_name='formular',
            name='max_vyska',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='pracovni_doba',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='pracovni_ukon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='souradnice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='specifika_pracoviste',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='zarizeni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formular',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formular',
            name='misto_prace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
