# Generated by Django 6.0.3 on 2026-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0005_remove_formular_popis_formular_max_vyska_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='postup_prace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='strom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
