# Generated by Django 6.0.3 on 2026-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0006_formular_postup_prace_formular_strom'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotky/'),
        ),
    ]
