# Generated by Django 6.0.3 on 2026-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0007_formular_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='vedouci_cinnost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='vedouci_jmeno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formular',
            name='vedouci_kvalifikace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Pracovnik',
        ),
    ]
